import { Option } from '@/src/resources/form';

export const cities = {
  PORT_BLAIR: 'Port Blair',
  VISAKHAPATNAM: 'Visakhapatnam',
  VIJAYAWADA: 'Vijayawada',
  GUNTUR: 'Guntur',
  NELLORE: 'Nellore',
  ITANAGAR: 'Itanagar',
  NAHARLAGUN: 'Naharlagun',
  GUWAHATI: 'Guwahati',
  SILCHAR: 'Silchar',
  DIBRUGARH: 'Dibrugarh',
  PATNA: 'Patna',
  GAYA: 'Gaya',
  BHAGALPUR: 'Bhagalpur',
  MUZAFFARPUR: 'Muzaffarpur',
  RAIPUR: 'Raipur',
  BHILAI: 'Bhilai',
  BILASPUR: 'Bilaspur',
  SILVASSA: 'Silvassa',
  DAMAN: 'Daman',
  DIU: 'Diu',
  NEW_DELHI: 'New Delhi',
  PANAJI: 'Panaji',
  MARGAO: 'Margao',
  AHMEDABAD: 'Ahmedabad',
  SURAT: 'Surat',
  VADODARA: 'Vadodara',
  RAJKOT: 'Rajkot',
  GURGAON: 'Gurgaon',
  FARIDABAD: 'Faridabad',
  PANIPAT: 'Panipat',
  SHIMLA: 'Shimla',
  MANALI: 'Manali',
  DHARAMSHALA: 'Dharamshala',
  SRINAGAR: 'Srinagar',
  JAMMU: 'Jammu',
  RANCHI: 'Ranchi',
  JAMSHEDPUR: 'Jamshedpur',
  DHANBAD: 'Dhanbad',
  BANGALORE: 'Bangalore',
  MYSORE: 'Mysore',
  MANGALORE: 'Mangalore',
  HUBLI: 'Hubli',
  KOCHI: 'Kochi',
  THIRUVANANTHAPURAM: 'Thiruvananthapuram',
  KOZHIKODE: 'Kozhikode',
  BHOPAL: 'Bhopal',
  INDORE: 'Indore',
  GWALIOR: 'Gwalior',
  JABALPUR: 'Jabalpur',
  MUMBAI: 'Mumbai',
  PUNE: 'Pune',
  NAGPUR: 'Nagpur',
  NASHIK: 'Nashik',
  IMPHAL: 'Imphal',
  SHILLONG: 'Shillong',
  AIZAWL: 'Aizawl',
  KOHIMA: 'Kohima',
  DIMAPUR: 'Dimapur',
  BHUBANESWAR: 'Bhubaneswar',
  CUTTACK: 'Cuttack',
  ROURKELA: 'Rourkela',
  LUDHIANA: 'Ludhiana',
  AMRITSAR: 'Amritsar',
  JALANDHAR: 'Jalandhar',
  PATIALA: 'Patiala',
  JAIPUR: 'Jaipur',
  JODHPUR: 'Jodhpur',
  UDAIPUR: 'Udaipur',
  KOTA: 'Kota',
  GANGTOK: 'Gangtok',
  CHENNAI: 'Chennai',
  COIMBATORE: 'Coimbatore',
  MADURAI: 'Madurai',
  TIRUCHIRAPPALLI: 'Tiruchirappalli',
  HYDERABAD: 'Hyderabad',
  WARANGAL: 'Warangal',
  AGARTALA: 'Agartala',
  LUCKNOW: 'Lucknow',
  KANPUR: 'Kanpur',
  GHAZIABAD: 'Ghaziabad',
  AGRA: 'Agra',
  DEHRADUN: 'Dehradun',
  HARIDWAR: 'Haridwar',
  KOLKATA: 'Kolkata',
  HOWRAH: 'Howrah',
  DURGAPUR: 'Durgapur',
  SILIGURI: 'Siliguri',
  KAVARATTI: 'Kavaratti',
  OTHER: 'Other',
};
export type City = keyof typeof cities;

export const states = {
  ANDAMAN_NICOBAR: 'Andaman & Nicobar Islands',
  ANDHRA_PRADESH: 'Andhra Pradesh',
  ARUNACHAL_PRADESH: 'Arunachal Pradesh',
  ASSAM: 'Assam',
  BIHAR: 'Bihar',
  CHHATTISGARH: 'Chhattisgarh',
  DADRA_NAGAR_HAVELI: 'Dadra & Nagar Haveli',
  DAMAN_DIU: 'Daman & Diu',
  DELHI: 'Delhi',
  GOA: 'Goa',
  GUJARAT: 'Gujarat',
  HARYANA: 'Haryana',
  HIMACHAL_PRADESH: 'Himachal Pradesh',
  JAMMU_KASHMIR: 'Jammu & Kashmir',
  JHARKHAND: 'Jharkhand',
  KARNATAKA: 'Karnataka',
  KERALA: 'Kerala',
  LAKSHADWEEP: 'Lakshadweep',
  MADHYA_PRADESH: 'Madhya Pradesh',
  MAHARASHTRA: 'Maharashtra',
  MANIPUR: 'Manipur',
  MEGHALAYA: 'Meghalaya',
  MIZORAM: 'Mizoram',
  NAGALAND: 'Nagaland',
  ODISHA: 'Odisha',
  PUNJAB: 'Punjab',
  RAJASTHAN: 'Rajasthan',
  SIKKIM: 'Sikkim',
  TAMIL_NADU: 'Tamil Nadu',
  TELANGANA: 'Telangana',
  TRIPURA: 'Tripura',
  UTTAR_PRADESH: 'Uttar Pradesh',
  UTTARAKHAND: 'Uttarakhand',
  WEST_BENGAL: 'West Bengal',
};
export type State = keyof typeof states;

export const stateCityMapping: Record<State, City[]> = {
  ANDAMAN_NICOBAR: ['PORT_BLAIR', 'OTHER'],
  ANDHRA_PRADESH: ['VISAKHAPATNAM', 'VIJAYAWADA', 'GUNTUR', 'NELLORE', 'OTHER'],
  ARUNACHAL_PRADESH: ['ITANAGAR', 'NAHARLAGUN', 'OTHER'],
  ASSAM: ['GUWAHATI', 'SILCHAR', 'DIBRUGARH', 'OTHER'],
  BIHAR: ['PATNA', 'GAYA', 'BHAGALPUR', 'MUZAFFARPUR', 'OTHER'],
  CHHATTISGARH: ['RAIPUR', 'BHILAI', 'BILASPUR', 'OTHER'],
  DADRA_NAGAR_HAVELI: ['SILVASSA', 'OTHER'],
  DAMAN_DIU: ['DAMAN', 'DIU', 'OTHER'],
  DELHI: ['NEW_DELHI', 'OTHER'],
  GOA: ['PANAJI', 'MARGAO', 'OTHER'],
  GUJARAT: ['AHMEDABAD', 'SURAT', 'VADODARA', 'RAJKOT', 'OTHER'],
  HARYANA: ['GURGAON', 'FARIDABAD', 'PANIPAT', 'OTHER'],
  HIMACHAL_PRADESH: ['SHIMLA', 'MANALI', 'DHARAMSHALA', 'OTHER'],
  JAMMU_KASHMIR: ['SRINAGAR', 'JAMMU', 'OTHER'],
  JHARKHAND: ['RANCHI', 'JAMSHEDPUR', 'DHANBAD', 'OTHER'],
  KARNATAKA: ['BANGALORE', 'MYSORE', 'MANGALORE', 'HUBLI', 'OTHER'],
  KERALA: ['KOCHI', 'THIRUVANANTHAPURAM', 'KOZHIKODE', 'OTHER'],
  LAKSHADWEEP: ['KAVARATTI', 'OTHER'],
  MADHYA_PRADESH: ['BHOPAL', 'INDORE', 'GWALIOR', 'JABALPUR', 'OTHER'],
  MAHARASHTRA: ['MUMBAI', 'PUNE', 'NAGPUR', 'NASHIK', 'OTHER'],
  MANIPUR: ['IMPHAL', 'OTHER'],
  MEGHALAYA: ['SHILLONG', 'OTHER'],
  MIZORAM: ['AIZAWL', 'OTHER'],
  NAGALAND: ['KOHIMA', 'DIMAPUR', 'OTHER'],
  ODISHA: ['BHUBANESWAR', 'CUTTACK', 'ROURKELA', 'OTHER'],
  PUNJAB: ['LUDHIANA', 'AMRITSAR', 'JALANDHAR', 'PATIALA', 'OTHER'],
  RAJASTHAN: ['JAIPUR', 'JODHPUR', 'UDAIPUR', 'KOTA', 'OTHER'],
  SIKKIM: ['GANGTOK', 'OTHER'],
  TAMIL_NADU: ['CHENNAI', 'COIMBATORE', 'MADURAI', 'TIRUCHIRAPPALLI', 'OTHER'],
  TELANGANA: ['HYDERABAD', 'WARANGAL', 'OTHER'],
  TRIPURA: ['AGARTALA', 'OTHER'],
  UTTAR_PRADESH: ['LUCKNOW', 'KANPUR', 'GHAZIABAD', 'AGRA', 'OTHER'],
  UTTARAKHAND: ['DEHRADUN', 'HARIDWAR', 'OTHER'],
  WEST_BENGAL: ['KOLKATA', 'HOWRAH', 'DURGAPUR', 'SILIGURI', 'OTHER'],
};

export const stateOptions: Option<State>[] = Object.keys(states).map(key => ({
  label: states[key as keyof typeof states],
  value: key as State,
}));

export const cityOptions = (state: State): Option<City>[] => {
  if (!state) return [];
  return stateCityMapping[state]
    ? stateCityMapping[state].map(value => ({
        label: cities[value as keyof typeof cities],
        value: value as City,
      }))
    : [];
};
