export const maritalStatus = {
  single: 'Single',
  married: 'Married',
  divorced: 'Divorced',
  widowed: 'Widowed',
  separated: 'Separated',
  neverMarried: 'Never Married',
};
export type MaritalStatus = keyof typeof maritalStatus;

export const motherTongues = {
  english: 'English',
  hindi: 'Hindi',
  bengali: 'Bengali',
  telugu: 'Telugu',
  tamil: 'Tamil',
  marathi: 'Marathi',
  urdu: 'Urdu',
  gujarati: 'Gujarati',
  malayalam: 'Malayalam',
  kannada: 'Kannada',
};
export type MotherTongue = keyof typeof motherTongues;
export const religions = {
  hindu: 'Hindu',
  muslim: 'Muslim',
  christian: 'Christian',
  sikh: 'Sikh',
  buddhist: 'Buddhist',
  jain: 'Jain',
  other: 'Other',
};
export type Religion = keyof typeof religions;
export const castes = {
  general: 'General',
  obc: 'OBC',
  sc: 'SC',
  st: 'ST',
  other: 'Other',
};
export type Caste = keyof typeof castes;
export const diets = {
  vegetarian: 'Vegetarian',
  nonVegetarian: 'Non-Vegetarian',
  vegan: 'Vegan',
  other: 'Other',
};
export type Diet = keyof typeof diets;
// export const cities = {
//   andamanNicobar: ['Port Blair', 'Other'],
//   andhraPradesh: ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Nellore', 'Other'],
//   arunachalPradesh: ['Itanagar', 'Naharlagun', 'Other'],
//   assam: ['Guwahati', 'Silchar', 'Dibrugarh', 'Other'],
//   bihar: ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Other'],
//   chhattisgarh: ['Raipur', 'Bhilai', 'Bilaspur', 'Other'],
//   dadraNagarHaveli: ['Silvassa', 'Other'],
//   damanDiu: ['Daman', 'Diu', 'Other'],
//   delhi: ['New Delhi', 'Other'],
//   goa: ['Panaji', 'Margao', 'Other'],
//   gujarat: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Other'],
//   haryana: ['Gurgaon', 'Faridabad', 'Panipat', 'Other'],
//   himachalPradesh: ['Shimla', 'Manali', 'Dharamshala', 'Other'],
//   jammuKashmir: ['Srinagar', 'Jammu', 'Other'],
//   jharkhand: ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Other'],
//   karnataka: ['Bangalore', 'Mysore', 'Mangalore', 'Hubli', 'Other'],
//   kerala: ['Kochi', 'Thiruvananthapuram', 'Kozhikode', 'Other'],
//   lakshadweep: ['Kavaratti', 'Other'],
//   madhyaPradesh: ['Bhopal', 'Indore', 'Gwalior', 'Jabalpur', 'Other'],
//   maharashtra: ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Other'],
//   manipur: ['Imphal', 'Other'],
//   meghalaya: ['Shillong', 'Other'],
//   mizoram: ['Aizawl', 'Other'],
//   nagaland: ['Kohima', 'Dimapur', 'Other'],
//   odisha: ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Other'],
//   other: ['Other'],
//   punjab: ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Other'],
//   rajasthan: ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Other'],
//   sikkim: ['Gangtok', 'Other'],
//   tamilNadu: ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Other'],
//   telangana: ['Hyderabad', 'Warangal', 'Other'],
//   tripura: ['Agartala', 'Other'],
//   uttarPradesh: ['Lucknow', 'Kanpur', 'Ghaziabad', 'Agra', 'Other'],
//   uttarakhand: ['Dehradun', 'Haridwar', 'Other'],
//   westBengal: ['kolkata', 'Howrah', 'Durgapur', 'Siliguri', 'Other'],
// };
// export type City = (typeof cities)[keyof typeof cities][number];

export const cities = {
  portBlair: 'Port Blair',
  visakhapatnam: 'Visakhapatnam',
  vijayawada: 'Vijayawada',
  guntur: 'Guntur',
  nellore: 'Nellore',
  itanagar: 'Itanagar',
  naharlagun: 'Naharlagun',
  guwahati: 'Guwahati',
  silchar: 'Silchar',
  dibrugarh: 'Dibrugarh',
  patna: 'Patna',
  gaya: 'Gaya',
  bhagalpur: 'Bhagalpur',
  muzaffarpur: 'Muzaffarpur',
  raipur: 'Raipur',
  bhilai: 'Bhilai',
  bilaspur: 'Bilaspur',
  silvassa: 'Silvassa',
  daman: 'Daman',
  diu: 'Diu',
  newDelhi: 'New Delhi',
  panaji: 'Panaji',
  margao: 'Margao',
  ahmedabad: 'Ahmedabad',
  surat: 'Surat',
  vadodara: 'Vadodara',
  rajkot: 'Rajkot',
  gurgaon: 'Gurgaon',
  faridabad: 'Faridabad',
  panipat: 'Panipat',
  shimla: 'Shimla',
  manali: 'Manali',
  dharamshala: 'Dharamshala',
  srinagar: 'Srinagar',
  jammu: 'Jammu',
  ranchi: 'Ranchi',
  jamshedpur: 'Jamshedpur',
  dhanbad: 'Dhanbad',
  bangalore: 'Bangalore',
  mysore: 'Mysore',
  mangalore: 'Mangalore',
  hubli: 'Hubli',
  kochi: 'Kochi',
  thiruvananthapuram: 'Thiruvananthapuram',
  kozhikode: 'Kozhikode',
  bhopal: 'Bhopal',
  indore: 'Indore',
  gwalior: 'Gwalior',
  jabalpur: 'Jabalpur',
  mumbai: 'Mumbai',
  pune: 'Pune',
  nagpur: 'Nagpur',
  nashik: 'Nashik',
  imphal: 'Imphal',
  shillong: 'Shillong',
  aizawl: 'Aizawl',
  kohima: 'Kohima',
  dimapur: 'Dimapur',
  bhubaneswar: 'Bhubaneswar',
  cuttack: 'Cuttack',
  rourkela: 'Rourkela',
  ludhiana: 'Ludhiana',
  amritsar: 'Amritsar',
  jalandhar: 'Jalandhar',
  patiala: 'Patiala',
  jaipur: 'Jaipur',
  jodhpur: 'Jodhpur',
  udaipur: 'Udaipur',
  kota: 'Kota',
  gangtok: 'Gangtok',
  chennai: 'Chennai',
  coimbatore: 'Coimbatore',
  madurai: 'Madurai',
  tiruchirappalli: 'Tiruchirappalli',
  hyderabad: 'Hyderabad',
  warangal: 'Warangal',
  agartala: 'Agartala',
  lucknow: 'Lucknow',
  kanpur: 'Kanpur',
  ghaziabad: 'Ghaziabad',
  agra: 'Agra',
  dehradun: 'Dehradun',
  haridwar: 'Haridwar',
  kolkata: 'Kolkata',
  howrah: 'Howrah',
  durgapur: 'Durgapur',
  siliguri: 'Siliguri',
  kavaratti: 'Kavaratti',
  other: 'Other',
};
export type City = keyof typeof cities;

export const educations = {
  noFormalEducation: 'No Formal Education',
  highSchool: 'High School',
  diploma: 'Diploma',
  bachelorDegree: "Bachelor's Degree",
  masterDegree: "Master's Degree",
  doctorate: 'Doctorate',
  other: 'Other',
};
export type Education = keyof typeof educations;
export const occupations = {
  engineer: 'Engineer',
  doctor: 'Doctor',
  teacher: 'Teacher',
  lawyer: 'Lawyer',
  artist: 'Artist',
  other: 'Other',
};
export type Occupation = keyof typeof occupations;
export const states = {
  andamanNicobar: 'Andaman & Nicobar Islands',
  andhraPradesh: 'Andhra Pradesh',
  arunachalPradesh: 'Arunachal Pradesh',
  assam: 'Assam',
  bihar: 'Bihar',
  chhattisgarh: 'Chhattisgarh',
  dadraNagarHaveli: 'Dadra & Nagar Haveli',
  damanDiu: 'Daman & Diu',
  delhi: 'Delhi',
  goa: 'Goa',
  gujarat: 'Gujarat',
  haryana: 'Haryana',
  himachalPradesh: 'Himachal Pradesh',
  jammuKashmir: 'Jammu & Kashmir',
  jharkhand: 'Jharkhand',
  karnataka: 'Karnataka',
  kerala: 'Kerala',
  lakshadweep: 'Lakshadweep',
  madhyaPradesh: 'Madhya Pradesh',
  maharashtra: 'Maharashtra',
  manipur: 'Manipur',
  meghalaya: 'Meghalaya',
  mizoram: 'Mizoram',
  nagaland: 'Nagaland',
  odisha: 'Odisha',
  punjab: 'Punjab',
  rajasthan: 'Rajasthan',
  sikkim: 'Sikkim',
  tamilNadu: 'Tamil Nadu',
  telangana: 'Telangana',
  tripura: 'Tripura',
  uttarPradesh: 'Uttar Pradesh',
  uttarakhand: 'Uttarakhand',
  westBengal: 'West Bengal',
};
export type State = keyof typeof states;

export const stateCityMapping: Record<State, City[]> = {
  andamanNicobar: ['portBlair', 'other'],
  andhraPradesh: ['visakhapatnam', 'vijayawada', 'guntur', 'nellore', 'other'],
  arunachalPradesh: ['itanagar', 'naharlagun', 'other'],
  assam: ['guwahati', 'silchar', 'dibrugarh', 'other'],
  bihar: ['patna', 'gaya', 'bhagalpur', 'muzaffarpur', 'other'],
  chhattisgarh: ['raipur', 'bhilai', 'bilaspur', 'other'],
  dadraNagarHaveli: ['silvassa', 'other'],
  damanDiu: ['daman', 'diu', 'other'],
  delhi: ['newDelhi', 'other'],
  goa: ['panaji', 'margao', 'other'],
  gujarat: ['ahmedabad', 'surat', 'vadodara', 'rajkot', 'other'],
  haryana: ['gurgaon', 'faridabad', 'panipat', 'other'],
  himachalPradesh: ['shimla', 'manali', 'dharamshala', 'other'],
  jammuKashmir: ['srinagar', 'jammu', 'other'],
  jharkhand: ['ranchi', 'jamshedpur', 'dhanbad', 'other'],
  karnataka: ['bangalore', 'mysore', 'mangalore', 'hubli', 'other'],
  kerala: ['kochi', 'thiruvananthapuram', 'kozhikode', 'other'],
  lakshadweep: ['kavaratti', 'other'],
  madhyaPradesh: ['bhopal', 'indore', 'gwalior', 'jabalpur', 'other'],
  maharashtra: ['mumbai', 'pune', 'nagpur', 'nashik', 'other'],
  manipur: ['imphal', 'other'],
  meghalaya: ['shillong', 'other'],
  mizoram: ['aizawl', 'other'],
  nagaland: ['kohima', 'dimapur', 'other'],
  odisha: ['bhubaneswar', 'cuttack', 'rourkela', 'other'],
  punjab: ['ludhiana', 'amritsar', 'jalandhar', 'patiala', 'other'],
  rajasthan: ['jaipur', 'jodhpur', 'udaipur', 'kota', 'other'],
  sikkim: ['gangtok', 'other'],
  tamilNadu: ['chennai', 'coimbatore', 'madurai', 'tiruchirappalli', 'other'],
  telangana: ['hyderabad', 'warangal', 'other'],
  tripura: ['agartala', 'other'],
  uttarPradesh: ['lucknow', 'kanpur', 'ghaziabad', 'agra', 'other'],
  uttarakhand: ['dehradun', 'haridwar', 'other'],
  westBengal: ['kolkata', 'howrah', 'durgapur', 'siliguri', 'other'],
};
